#!/bin/bash

echo "🔧 Unit Map Fix Script"
echo "======================"
echo ""
echo "This script will help you fix the unit map display issue."
echo "The problem is that files with spaces in their paths cause 400 errors."
echo ""
echo "Steps:"
echo "1. Run the migration to clear broken unit map references"
echo "2. Re-upload unit map images (they will use the correct path format)"
echo ""
echo "Migration files to run:"
echo "- 20250120000009_fix_files_table_rls_only.sql (RLS policies)"
echo "- 20250120000012_clear_broken_unit_maps.sql (clear broken references)"
echo ""
echo "After running the migrations:"
echo "1. Go to the property edit page"
echo "2. Upload the unit map image again"
echo "3. The new upload will use the sanitized path format"
echo ""
echo "The file upload function has been updated to automatically"
echo "sanitize property names (spaces → underscores) to prevent this issue."
echo ""
echo "Ready to proceed? Run the migrations in your Supabase dashboard."
