/**
 * SMS Notification Settings — shared types
 *
 * This file is the single canonical source of truth for all SMS notification
 * types that need to be shared across multiple modules (service layer, hooks,
 * components, edge functions).
 *
 * Import from here rather than from the service module to avoid circular deps.
 *
 * ─── Role eligibility reference ─────────────────────────────────────────────
 *
 *   Subcontractors:              chat_received, job_assigned, charges_approved
 *   Admins / Super Admins:       chat_received, work_order_submitted, job_accepted
 *                                (+ optionally job_assigned, charges_approved)
 *   JG Management:               same as Admins / Super Admins
 *
 * Role eligibility is enforced at the UI / API layer, NOT in the database.
 * The DB stores all five flag columns for every user regardless of role,
 * ensuring the schema never needs to change when eligibility rules evolve.
 * ─────────────────────────────────────────────────────────────────────────────
 */

// ─── Notification event keys ──────────────────────────────────────────────────

/**
 * All valid SMS notification event keys.
 * Each key maps directly to a `notify_*` boolean column in
 * user_sms_notification_settings.
 */
export type SmsNotificationEventKey =
  | 'chat_received'
  | 'job_assigned'
  | 'charges_approved'
  | 'work_order_submitted'
  | 'job_accepted';

// ─── Role types ───────────────────────────────────────────────────────────────

/**
 * The subset of profiles.role values that are considered SMS-eligible.
 * Maps to the CHECK constraint on profiles.role.
 */
export type SmsEligibleRole =
  | 'subcontractor'
  | 'admin'
  | 'is_super_admin'
  | 'jg_management';

// ─── Database row shape ───────────────────────────────────────────────────────

/**
 * Exact shape of a row in public.user_sms_notification_settings.
 * Field names and types match the Postgres schema 1:1.
 *
 * Phone numbers are NEVER stored here.
 * They come exclusively from profiles.sms_phone.
 */
export interface UserSmsNotificationSettings {
  /** Primary key — uuid generated by the DB. Never set by the application. */
  id: string;
  /** FK → profiles.id (= auth.users.id). One row per user. */
  user_id: string;
  /**
   * Master on/off switch.
   * When false, all notify_* flags are ignored by the dispatcher.
   */
  sms_enabled: boolean;
  /** Notify on new inbound chat message. Applies to all roles. */
  notify_chat_received: boolean;
  /** Notify when a job is assigned to this user. Primary: subcontractors. */
  notify_job_assigned: boolean;
  /** Notify when extra charges are approved. Primary: subcontractors. */
  notify_charges_approved: boolean;
  /** Notify when a new work order is submitted. Primary: admin / super admin. */
  notify_work_order_submitted: boolean;
  /** Notify when a subcontractor accepts a job. Primary: admin / super admin. */
  notify_job_accepted: boolean;
  /** Row creation timestamp (UTC). Set by DB default. */
  created_at: string;
  /** Last-updated timestamp (UTC). Maintained by the update_updated_at_column trigger. */
  updated_at: string;
}

// ─── Write payload types ──────────────────────────────────────────────────────

/**
 * The writable subset of UserSmsNotificationSettings.
 * Used for INSERT / UPDATE payloads.
 * Omits: id, user_id, created_at, updated_at (all DB-managed).
 */
export type UserSmsNotificationSettingsUpdate = Pick<
  UserSmsNotificationSettings,
  | 'sms_enabled'
  | 'notify_chat_received'
  | 'notify_job_assigned'
  | 'notify_charges_approved'
  | 'notify_work_order_submitted'
  | 'notify_job_accepted'
>;

// ─── With-profile join type (admin queries) ───────────────────────────────────

/**
 * Returned by getAllSmsSettings() — the settings row joined with
 * the essential fields from profiles.
 * Allows admin UIs to show name / role / phone alongside each settings row
 * without a separate query.
 */
export interface UserSmsNotificationSettingsWithProfile
  extends UserSmsNotificationSettings {
  profile: {
    full_name: string | null;
    email: string;
    role: string;
    /** E.164 U.S. format (+1XXXXXXXXXX) or null if not set. */
    sms_phone: string | null;
  };
}

// ─── Dispatcher helper type ───────────────────────────────────────────────────

/**
 * Return value from shouldSendSmsForEvent().
 * Used by the future SMS dispatcher to decide whether to send a message.
 */
export interface SmsSendEligibilityResult {
  /** Whether all conditions are met and an SMS should be sent. */
  should: boolean;
  /**
   * The user's E.164 phone number, or null if not set.
   * Present even when should = false so the caller can log the phone separately.
   */
  phone: string | null;
  /** Human-readable explanation. 'OK' when should = true. */
  reason: string;
}

// ─── Eligibility map ──────────────────────────────────────────────────────────

/**
 * Maps each profiles.role value to the SMS events that role is eligible for.
 * Application code uses this to show / hide toggles in the UI and to guard
 * against unintended flag writes.
 *
 * The DB does NOT enforce this — it stores all columns for all users.
 * Eligibility is a UI/API-layer concern only.
 */
export const SMS_ROLE_ELIGIBILITY: Record<string, SmsNotificationEventKey[]> = {
  subcontractor: ['chat_received', 'job_assigned', 'charges_approved'],
  admin: [
    'chat_received',
    'work_order_submitted',
    'job_accepted',
    'job_assigned',
    'charges_approved',
  ],
  is_super_admin: [
    'chat_received',
    'work_order_submitted',
    'job_accepted',
    'job_assigned',
    'charges_approved',
  ],
  jg_management: [
    'chat_received',
    'work_order_submitted',
    'job_accepted',
    'job_assigned',
    'charges_approved',
  ],
} as const;

/**
 * Returns the eligible SMS event keys for a given profiles.role value.
 * Unknown roles receive an empty array (no eligibility, no error).
 */
export function getSmsEligibleEvents(role: string): SmsNotificationEventKey[] {
  return SMS_ROLE_ELIGIBILITY[role] ?? [];
}

// ─── Event metadata ───────────────────────────────────────────────────────────

/**
 * Human-readable labels for each event key.
 * Use in settings UIs and notification templates.
 */
export const SMS_EVENT_LABELS: Record<SmsNotificationEventKey, string> = {
  chat_received: 'New Chat Message',
  job_assigned: 'Job Assigned',
  charges_approved: 'Extra Charges Approved',
  work_order_submitted: 'Work Order Submitted',
  job_accepted: 'Job Accepted',
} as const;

/**
 * Maps each event key to its corresponding notify_* column name.
 * Use when constructing dynamic DB queries or field update payloads.
 */
export const SMS_EVENT_TO_FIELD: Record<
  SmsNotificationEventKey,
  keyof UserSmsNotificationSettingsUpdate
> = {
  chat_received: 'notify_chat_received',
  job_assigned: 'notify_job_assigned',
  charges_approved: 'notify_charges_approved',
  work_order_submitted: 'notify_work_order_submitted',
  job_accepted: 'notify_job_accepted',
} as const;

// ─── Default values ───────────────────────────────────────────────────────────

/**
 * Safe default values for a new settings row.
 * All flags are false (opt-in model — nothing is enabled by default).
 * Matches the DB column defaults exactly.
 */
export const SMS_SETTINGS_DEFAULTS: UserSmsNotificationSettingsUpdate = {
  sms_enabled: false,
  notify_chat_received: false,
  notify_job_assigned: false,
  notify_charges_approved: false,
  notify_work_order_submitted: false,
  notify_job_accepted: false,
} as const;
