-- Migration: add_sms_notification_settings_to_profiles
-- NOTE: This migration was created in error. The notify_* columns already exist
-- in the user_sms_notification_settings table, which is the correct location.
-- This migration adds duplicate columns to profiles, which have been removed.
--
-- Correct table structure:
--   - user_sms_notification_settings: Contains all notify_* columns (correct)
--   - profiles: Contains sms_phone, sms_consent_given, etc. (correct)
--
-- This file is kept for migration history but performs no action.

-- No changes needed - columns already exist in user_sms_notification_settings table
